# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]


jobs:        
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run Checkstyle
      run: ant run-check

    #- name: Run super-linter on Project
    #  uses: github/super-linter@v3
    #  env:
    #      DEFAULT_BRANCH: main
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarCloud Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Creat javadoc
      run: ant create-doc
      
    - name: Compile project
      run: ant compile
      
    - name: Run tests
      run: ant compile-tests run-check
      
    - name: Add 2 to 3
      run: java -cp bin AdditionProgram 2 3
